version: '3.3'

networks:
  web:
    external: true

services:
  nginx:
    restart: always
    image: nginx:alpine
    networks:
    - web
    ports:
    - 80
    volumes:
    - ./www:/srv/www:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
    - traefik.http.routers.{{ home.split('/')[-1] }}.rule=Host(`{{ url.split('/')[2] }}`)
{% if url.startswith('https') %}
    - traefik.http.routers.{{ home.split('/')[-1] }}.tls.certresolver=leresolver
    - traefik.http.routers.{{ home.split('/')[-1] }}.entrypoints=websecure
{% endif %}

  mirror:
    restart: always
    image: alpine
    command: sh -c "./mirror.sh; while ./mirror.sh; do sleep 3600; done"
    working_dir: /srv
    volumes:
    - .:/srv:rw
