version: '3.3'

networks:
  web:
    external: true

services:
  nginx:
    image: nginx:alpine
    networks:
    - web
    ports:
    - 80
    volumes:
    - ./www:/usr/share/nginx/html:ro
    labels:
    - traefik.http.routers.mirror.rule=Host(`{{ url.split("/")[2] }}`)

  mirror:
    image: alpine
    command: sh -c "./mirror.sh; while ./mirror.sh; do sleep 3600; done"
    working_dir: /srv
    volumes:
    - .:/srv:rw
